name: Build and publish to Nuget on GitHub packages

on:
  push:
    branches: [ V1 ]
    paths:
    - 'src/GitHubHelper/**'
  pull_request:
    branches: [ V1 ]
    paths:
    - 'src/GitHubHelper/**'

  workflow_dispatch:

jobs:
  build:
    env:
      working-directory: ./src/GitHubHelper
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ${{env.working-directory}}/bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/lbugnion/index.json --skip-duplicate --no-symbols true
      working-directory: ${{env.working-directory}}
